<?php

namespace App\Badanie\BadanieBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BadanieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BadanieRepository extends EntityRepository
{
}
